version: "3.8"

services:
  api-service-test:
    image: api-service-test
    container_name: api-test
    build:
      context: api-service
      target: test
    volumes:
      - ./api-service/src:/app/src
      - ./api-service/tests:/app/tests
      - ./api-service/poetry.lock:/app/poetry.lock
      - ./api-service/pyproject.toml:/app/pyproject.toml

volumes:
  main-db:
    external: false
  keycloak-db:
    external: false

networks:
  strain_network:
    external: false