version: '3.9'

services:
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./teamcity.conf:/etc/nginx/conf.d/default.conf
  teamcity-server:
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-conf:/opt/teamcity/conf
      - teamcity-logs:/opt/teamcity/logs
  teamcity-database:
    environment:
      - POSTGRES_DB=teamcity
      - POSTGRES_USER=teamcity
      - POSTGRES_PASSWORD=teamcity

volumes:
  teamcity-data:
  teamcity-conf:
  teamcity-logs:
