export enum SharedClassNameEnum {
  TEXT_48_BOLD = 'shared-text-48-bold',
  TEXT_40_BOLD = 'shared-text-40-bold',
  TEXT_32_BOLD = 'shared-text-32-bold',
  TEXT_28_BOLD = 'shared-text-28-bold',
  TEXT_24_BOLD = 'shared-text-24-bold',
  TEXT_20_BOLD = 'shared-text-20-bold',
  TEXT_18_BOLD = 'shared-text-18-bold',
  TEXT_16_BOLD = 'shared-text-16-bold',
  TEXT_14_BOLD = 'shared-text-14-bold',
  TEXT_12_BOLD = 'shared-text-12-bold',
  TEXT_10_BOLD = 'shared-text-10-bold',

  TEXT_48_REGULAR = 'shared-text-40-regular',
  TEXT_40_REGULAR = 'shared-text-48-regular',
  TEXT_32_REGULAR = 'shared-text-32-regular',
  TEXT_28_REGULAR = 'shared-text-28-regular',
  TEXT_24_REGULAR = 'shared-text-24-regular',
  TEXT_20_REGULAR = 'shared-text-20-regular',
  TEXT_18_REGULAR = 'shared-text-18-regular',
  TEXT_16_REGULAR = 'shared-text-16-regular',
  TEXT_14_REGULAR = 'shared-text-14-regular',
  TEXT_12_REGULAR = 'shared-text-12-regular',
  TEXT_10_REGULAR = 'shared-text-10-regular',

  TEXT_ERROR = 'shared-text-error',

  GRID = 'shared-grid',
  GRID_2 = 'shared-grid-column-2',
  GRID_3 = 'shared-grid-column-3',
  GRID_4 = 'shared-grid-column-4',
}
